# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc81c38c8bc4242ff9dc2a81092990f2"
name = "sn-popup"
handle = "sn-popup"
application_url = "https://shipments-freeze-northeast-booking.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lionel-tao.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_script_tags,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://shipments-freeze-northeast-booking.trycloudflare.com/auth/callback",
  "https://shipments-freeze-northeast-booking.trycloudflare.com/auth/shopify/callback",
  "https://shipments-freeze-northeast-booking.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
